[tool.poetry]
name = "sc2city"
version = "0.1.0"
description = ""
authors = ["savelas81 <savelas81@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
